var Arcoviola = new Tone.Sampler({
  "A.A4" : "./Instruments/Strings/Viola/Arco/A.A4.mp3",
  "A.A5" : "./Instruments/Strings/Viola/Arco/A.A5.mp3",
  "A.A6" : "./Instruments/Strings/Viola/Arco/A.A6.mp3",
  "A.Ab5" : "./Instruments/Strings/Viola/Arco/A.Ab5.mp3",
  "A.Ab6" : "./Instruments/Strings/Viola/Arco/A.Ab6.mp3",
  "A.B4" : "./Instruments/Strings/Viola/Arco/A.B4.mp3",
  "A.B5" : "./Instruments/Strings/Viola/Arco/A.B5.mp3",
  "A.Bb4" : "./Instruments/Strings/Viola/Arco/A.Bb4.mp3",
  "A.Bb5" : "./Instruments/Strings/Viola/Arco/A.Bb5.mp3",
  "A.C5" : "./Instruments/Strings/Viola/Arco/A.C5.mp3",
  "A.C6" : "./Instruments/Strings/Viola/Arco/A.C6.mp3",
  "A.D5" : "./Instruments/Strings/Viola/Arco/A.D5.mp3",
  "A.D6" : "./Instruments/Strings/Viola/Arco/A.D6.mp3",
  "A.Db5" : "./Instruments/Strings/Viola/Arco/A.Db5.mp3",
  "A.Db6" : "./Instruments/Strings/Viola/Arco/A.Db6.mp3",
  "A.E5" : "./Instruments/Strings/Viola/Arco/A.E5.mp3",
  "A.E6" : "./Instruments/Strings/Viola/Arco/A.E6.mp3",
  "A.Eb5" : "./Instruments/Strings/Viola/Arco/A.Eb5.mp3",
  "A.Eb6" : "./Instruments/Strings/Viola/Arco/A.Eb6.mp3",
  "A.F5" : "./Instruments/Strings/Viola/Arco/A.F5.mp3",
  "A.F6" : "./Instruments/Strings/Viola/Arco/A.F6.mp3",
  "A.G5" : "./Instruments/Strings/Viola/Arco/A.G5.mp3",
  "A.G6" : "./Instruments/Strings/Viola/Arco/A.G6.mp3",
  "A.Gb5" : "./Instruments/Strings/Viola/Arco/A.Gb5.mp3",
  "C.A3" : "./Instruments/Strings/Viola/Arco/C.A3.mp3",
  "C.A4" : "./Instruments/Strings/Viola/Arco/C.A4.mp3",
  "C.Ab3" : "./Instruments/Strings/Viola/Arco/C.Ab3.mp3",
  "C.Ab4" : "./Instruments/Strings/Viola/Arco/C.Ab4.mp3",
  "C.B3" : "./Instruments/Strings/Viola/Arco/C.B3.mp3",
  "C.B4" : "./Instruments/Strings/Viola/Arco/C.B4.mp3",
  "C.Bb3" : "./Instruments/Strings/Viola/Arco/C.Bb3.mp3",
  "C.Bb4" : "./Instruments/Strings/Viola/Arco/C.Bb4.mp3",
  "C.C3" : "./Instruments/Strings/Viola/Arco/C.C3.mp3",
  "C.C4" : "./Instruments/Strings/Viola/Arco/C.C4.mp3",
  "C.C5" : "./Instruments/Strings/Viola/Arco/C.C5.mp3",
  "C.D3" : "./Instruments/Strings/Viola/Arco/C.D3.mp3",
  "C.D4" : "./Instruments/Strings/Viola/Arco/C.D4.mp3",
  "C.Db3" : "./Instruments/Strings/Viola/Arco/C.Db3.mp3",
  "C.Db4" : "./Instruments/Strings/Viola/Arco/C.Db4.mp3",
  "C.E3" : "./Instruments/Strings/Viola/Arco/C.E3.mp3",
  "C.E4" : "./Instruments/Strings/Viola/Arco/C.E4.mp3",
  "C.Eb3" : "./Instruments/Strings/Viola/Arco/C.Eb3.mp3",
  "C.Eb4" : "./Instruments/Strings/Viola/Arco/C.Eb4.mp3",
  "C.F3" : "./Instruments/Strings/Viola/Arco/C.F3.mp3",
  "C.F4" : "./Instruments/Strings/Viola/Arco/C.F4.mp3",
  "C.G3" : "./Instruments/Strings/Viola/Arco/C.G3.mp3",
  "C.G4" : "./Instruments/Strings/Viola/Arco/C.G4.mp3",
  "C.Gb3" : "./Instruments/Strings/Viola/Arco/C.Gb3.mp3",
  "C.Gb4" : "./Instruments/Strings/Viola/Arco/C.Gb4.mp3",
  "D.A4" : "./Instruments/Strings/Viola/Arco/D.A4.mp3",
  "D.A5" : "./Instruments/Strings/Viola/Arco/D.A5.mp3",
  "D.Ab4" : "./Instruments/Strings/Viola/Arco/D.Ab4.mp3",
  "D.Ab5" : "./Instruments/Strings/Viola/Arco/D.Ab5.mp3",
  "D.B4" : "./Instruments/Strings/Viola/Arco/D.B4.mp3",
  "D.B5" : "./Instruments/Strings/Viola/Arco/D.B5.mp3",
  "D.Bb4" : "./Instruments/Strings/Viola/Arco/D.Bb4.mp3",
  "D.Bb5" : "./Instruments/Strings/Viola/Arco/D.Bb5.mp3",
  "D.C5" : "./Instruments/Strings/Viola/Arco/D.C5.mp3",
  "D.C6" : "./Instruments/Strings/Viola/Arco/D.C6.mp3",
  "D.D4" : "./Instruments/Strings/Viola/Arco/D.D4.mp3",
  "D.D5" : "./Instruments/Strings/Viola/Arco/D.D5.mp3",
  "D.D6" : "./Instruments/Strings/Viola/Arco/D.D6.mp3",
  "D.Db5" : "./Instruments/Strings/Viola/Arco/D.Db5.mp3",
  "D.Db6" : "./Instruments/Strings/Viola/Arco/D.Db6.mp3",
  "D.E4" : "./Instruments/Strings/Viola/Arco/D.E4.mp3",
  "D.E5" : "./Instruments/Strings/Viola/Arco/D.E5.mp3",
  "D.Eb4" : "./Instruments/Strings/Viola/Arco/D.Eb4.mp3",
  "D.Eb5" : "./Instruments/Strings/Viola/Arco/D.Eb5.mp3",
  "D.F4" : "./Instruments/Strings/Viola/Arco/D.F4.mp3",
  "D.F5" : "./Instruments/Strings/Viola/Arco/D.F5.mp3",
  "D.G4" : "./Instruments/Strings/Viola/Arco/D.G4.mp3",
  "D.G5" : "./Instruments/Strings/Viola/Arco/D.G5.mp3",
  "D.Gb4" : "./Instruments/Strings/Viola/Arco/D.Gb4.mp3",
  "D.Gb5" : "./Instruments/Strings/Viola/Arco/D.Gb5.mp3",
  "G.A3" : "./Instruments/Strings/Viola/Arco/G.A3.mp3",
  "G.A4" : "./Instruments/Strings/Viola/Arco/G.A4.mp3",
  "G.Ab3" : "./Instruments/Strings/Viola/Arco/G.Ab3.mp3",
  "G.Ab4" : "./Instruments/Strings/Viola/Arco/G.Ab4.mp3",
  "G.B3" : "./Instruments/Strings/Viola/Arco/G.B3.mp3",
  "G.B4" : "./Instruments/Strings/Viola/Arco/G.B4.mp3",
  "G.Bb3" : "./Instruments/Strings/Viola/Arco/G.Bb3.mp3",
  "G.Bb4" : "./Instruments/Strings/Viola/Arco/G.Bb4.mp3",
  "G.C4" : "./Instruments/Strings/Viola/Arco/G.C4.mp3",
  "G.C5" : "./Instruments/Strings/Viola/Arco/G.C5.mp3",
  "G.D4" : "./Instruments/Strings/Viola/Arco/G.D4.mp3",
  "G.D5" : "./Instruments/Strings/Viola/Arco/G.D5.mp3",
  "G.Db4" : "./Instruments/Strings/Viola/Arco/G.Db4.mp3",
  "G.Db5" : "./Instruments/Strings/Viola/Arco/G.Db5.mp3",
  "G.E4" : "./Instruments/Strings/Viola/Arco/G.E4.mp3",
  "G.E5" : "./Instruments/Strings/Viola/Arco/G.E5.mp3",
  "G.Eb4" : "./Instruments/Strings/Viola/Arco/G.Eb4.mp3",
  "G.Eb5" : "./Instruments/Strings/Viola/Arco/G.Eb5.mp3",
  "G.F4" : "./Instruments/Strings/Viola/Arco/G.F4.mp3",
  "G.F5" : "./Instruments/Strings/Viola/Arco/G.F5.mp3",
  "G.G3" : "./Instruments/Strings/Viola/Arco/G.G3.mp3",
  "G.G4" : "./Instruments/Strings/Viola/Arco/G.G4.mp3",
  "G.G5" : "./Instruments/Strings/Viola/Arco/G.G5.mp3",
  "G.Gb4" : "./Instruments/Strings/Viola/Arco/G.Gb4.mp3",
  "G.Gb5" : "./Instruments/Strings/Viola/Arco/G.Gb5.mp3",
});
var Pizzviola = new Tone.Sampler({
  "PizzA.A4" : "./Instruments/Strings/Viola/Pizzicato/PizzA.A4.mp3",
  "PizzA.A5" : "./Instruments/Strings/Viola/Pizzicato/PizzA.A5.mp3",
  "PizzA.A6" : "./Instruments/Strings/Viola/Pizzicato/PizzA.A6.mp3",
  "PizzA.Ab5" : "./Instruments/Strings/Viola/Pizzicato/PizzA.Ab5.mp3",
  "PizzA.Ab6" : "./Instruments/Strings/Viola/Pizzicato/PizzA.Ab6.mp3",
  "PizzA.B4" : "./Instruments/Strings/Viola/Pizzicato/PizzA.B4.mp3",
  "PizzA.B5" : "./Instruments/Strings/Viola/Pizzicato/PizzA.B5.mp3",
  "PizzA.Bb4" : "./Instruments/Strings/Viola/Pizzicato/PizzA.Bb4.mp3",
  "PizzA.Bb5" : "./Instruments/Strings/Viola/Pizzicato/PizzA.Bb5.mp3",
  "PizzA.C5" : "./Instruments/Strings/Viola/Pizzicato/PizzA.C5.mp3",
  "PizzA.C6" : "./Instruments/Strings/Viola/Pizzicato/PizzA.C6.mp3",
  "PizzA.D5" : "./Instruments/Strings/Viola/Pizzicato/PizzA.D5.mp3",
  "PizzA.D6" : "./Instruments/Strings/Viola/Pizzicato/PizzA.D6.mp3",
  "PizzA.Db5" : "./Instruments/Strings/Viola/Pizzicato/PizzA.Db5.mp3",
  "PizzA.Db6" : "./Instruments/Strings/Viola/Pizzicato/PizzA.Db6.mp3",
  "PizzA.E5" : "./Instruments/Strings/Viola/Pizzicato/PizzA.E5.mp3",
  "PizzA.E6" : "./Instruments/Strings/Viola/Pizzicato/PizzA.E6.mp3",
  "PizzA.Eb5" : "./Instruments/Strings/Viola/Pizzicato/PizzA.Eb5.mp3",
  "PizzA.Eb6" : "./Instruments/Strings/Viola/Pizzicato/PizzA.Eb6.mp3",
  "PizzA.F5" : "./Instruments/Strings/Viola/Pizzicato/PizzA.F5.mp3",
  "PizzA.F6" : "./Instruments/Strings/Viola/Pizzicato/PizzA.F6.mp3",
  "PizzA.G5" : "./Instruments/Strings/Viola/Pizzicato/PizzA.G5.mp3",
  "PizzA.G6" : "./Instruments/Strings/Viola/Pizzicato/PizzA.G6.mp3",
  "PizzA.Gb5" : "./Instruments/Strings/Viola/Pizzicato/PizzA.Gb5.mp3",
  "PizzA.Gb6" : "./Instruments/Strings/Viola/Pizzicato/PizzA.Gb6.mp3",
  "PizzC.A3" : "./Instruments/Strings/Viola/Pizzicato/PizzC.A3.mp3",
  "PizzC.A4" : "./Instruments/Strings/Viola/Pizzicato/PizzC.A4.mp3",
  "PizzC.Ab3" : "./Instruments/Strings/Viola/Pizzicato/PizzC.Ab3.mp3",
  "PizzC.Ab4" : "./Instruments/Strings/Viola/Pizzicato/PizzC.Ab4.mp3",
  "PizzC.B3" : "./Instruments/Strings/Viola/Pizzicato/PizzC.B3.mp3",
  "PizzC.B4" : "./Instruments/Strings/Viola/Pizzicato/PizzC.B4.mp3",
  "PizzC.Bb3" : "./Instruments/Strings/Viola/Pizzicato/PizzC.Bb3.mp3",
  "PizzC.Bb4" : "./Instruments/Strings/Viola/Pizzicato/PizzC.Bb4.mp3",
  "PizzC.C3" : "./Instruments/Strings/Viola/Pizzicato/PizzC.C3.mp3",
  "PizzC.C4" : "./Instruments/Strings/Viola/Pizzicato/PizzC.C4.mp3",
  "PizzC.C5" : "./Instruments/Strings/Viola/Pizzicato/PizzC.C5.mp3",
  "PizzC.D3" : "./Instruments/Strings/Viola/Pizzicato/PizzC.D3.mp3",
  "PizzC.D4" : "./Instruments/Strings/Viola/Pizzicato/PizzC.D4.mp3",
  "PizzC.Db3" : "./Instruments/Strings/Viola/Pizzicato/PizzC.Db3.mp3",
  "PizzC.Db4" : "./Instruments/Strings/Viola/Pizzicato/PizzC.Db4.mp3",
  "PizzC.E3" : "./Instruments/Strings/Viola/Pizzicato/PizzC.E3.mp3",
  "PizzC.E4" : "./Instruments/Strings/Viola/Pizzicato/PizzC.E4.mp3",
  "PizzC.Eb3" : "./Instruments/Strings/Viola/Pizzicato/PizzC.Eb3.mp3",
  "PizzC.Eb4" : "./Instruments/Strings/Viola/Pizzicato/PizzC.Eb4.mp3",
  "PizzC.F3" : "./Instruments/Strings/Viola/Pizzicato/PizzC.F3.mp3",
  "PizzC.F4" : "./Instruments/Strings/Viola/Pizzicato/PizzC.F4.mp3",
  "PizzC.G3" : "./Instruments/Strings/Viola/Pizzicato/PizzC.G3.mp3",
  "PizzC.G4" : "./Instruments/Strings/Viola/Pizzicato/PizzC.G4.mp3",
  "PizzC.Gb3" : "./Instruments/Strings/Viola/Pizzicato/PizzC.Gb3.mp3",
  "PizzC.Gb4" : "./Instruments/Strings/Viola/Pizzicato/PizzC.Gb4.mp3",
  "PizzD.A4" : "./Instruments/Strings/Viola/Pizzicato/PizzD.A4.mp3",
  "PizzD.A5" : "./Instruments/Strings/Viola/Pizzicato/PizzD.A5.mp3",
  "PizzD.Ab4" : "./Instruments/Strings/Viola/Pizzicato/PizzD.Ab4.mp3",
  "PizzD.Ab5" : "./Instruments/Strings/Viola/Pizzicato/PizzD.A5.mp3",
  "PizzD.B4" : "./Instruments/Strings/Viola/Pizzicato/PizzD.B4.mp3",
  "PizzD.B5" : "./Instruments/Strings/Viola/Pizzicato/PizzD.B5.mp3",
  "PizzD.Bb4" : "./Instruments/Strings/Viola/Pizzicato/PizzD.Bb4.mp3",
  "PizzD.Bb5" : "./Instruments/Strings/Viola/Pizzicato/PizzD.Bb5.mp3",
  "PizzD.C5" : "./Instruments/Strings/Viola/Pizzicato/PizzD.C5.mp3",
  "PizzD.C6" : "./Instruments/Strings/Viola/Pizzicato/PizzD.C6.mp3",
  "PizzD.D4" : "./Instruments/Strings/Viola/Pizzicato/PizzD.D4.mp3",
  "PizzD.D5" : "./Instruments/Strings/Viola/Pizzicato/PizzD.D5.mp3",
  "PizzD.D6" : "./Instruments/Strings/Viola/Pizzicato/PizzD.D6.mp3",
  "PizzD.Db5" : "./Instruments/Strings/Viola/Pizzicato/PizzD.Db5.mp3",
  "PizzD.Db6" : "./Instruments/Strings/Viola/Pizzicato/PizzD.Db6.mp3",
  "PizzD.E4" : "./Instruments/Strings/Viola/Pizzicato/PizzD.E4.mp3",
  "PizzD.E5" : "./Instruments/Strings/Viola/Pizzicato/PizzD.E5.mp3",
  "PizzD.Eb4" : "./Instruments/Strings/Viola/Pizzicato/PizzD.Eb4.mp3",
  "PizzD.Eb5" : "./Instruments/Strings/Viola/Pizzicato/PizzD.Eb5.mp3",
  "PizzD.F4" : "./Instruments/Strings/Viola/Pizzicato/PizzD.F4.mp3",
  "PizzD.F5" : "./Instruments/Strings/Viola/Pizzicato/PizzD.F5.mp3",
  "PizzD.G4" : "./Instruments/Strings/Viola/Pizzicato/PizzD.G4.mp3",
  "PizzD.G5" : "./Instruments/Strings/Viola/Pizzicato/PizzD.G5.mp3",
  "PizzD.Gb4" : "./Instruments/Strings/Viola/Pizzicato/PizzD.Gb4.mp3",
  "PizzD.Gb5" : "./Instruments/Strings/Viola/Pizzicato/PizzD.Gb5.mp3",
  "PizzG.A3" : "./Instruments/Strings/Viola/Pizzicato/PizzG.A3.mp3",
  "PizzG.A4" : "./Instruments/Strings/Viola/Pizzicato/PizzG.A4.mp3",
  "PizzG.Ab3" : "./Instruments/Strings/Viola/Pizzicato/PizzG.Ab3.mp3",
  "PizzG.Ab4" : "./Instruments/Strings/Viola/Pizzicato/PizzG.Ab4.mp3",
  "PizzG.B3" : "./Instruments/Strings/Viola/Pizzicato/PizzG.B3.mp3",
  "PizzG.B4" : "./Instruments/Strings/Viola/Pizzicato/PizzG.B4.mp3",
  "PizzG.Bb3" : "./Instruments/Strings/Viola/Pizzicato/PizzG.Bb3.mp3",
  "PizzG.Bb4" : "./Instruments/Strings/Viola/Pizzicato/PizzG.Bb4.mp3",
  "PizzG.C4" : "./Instruments/Strings/Viola/Pizzicato/PizzG.C4.mp3",
  "PizzG.C5" : "./Instruments/Strings/Viola/Pizzicato/PizzG.C5.mp3",
  "PizzG.D4" : "./Instruments/Strings/Viola/Pizzicato/PizzG.D4.mp3",
  "PizzG.D5" : "./Instruments/Strings/Viola/Pizzicato/PizzG.D5.mp3",
  "PizzG.Db4" : "./Instruments/Strings/Viola/Pizzicato/PizzG.Db4.mp3",
  "PizzG.Db5" : "./Instruments/Strings/Viola/Pizzicato/PizzG.Db5.mp3",
  "PizzG.E4" : "./Instruments/Strings/Viola/Pizzicato/PizzG.E4.mp3",
  "PizzG.E5" : "./Instruments/Strings/Viola/Pizzicato/PizzG.E5.mp3",
  "PizzG.Eb4" : "./Instruments/Strings/Viola/Pizzicato/PizzG.Eb4.mp3",
  "PizzG.Eb5" : "./Instruments/Strings/Viola/Pizzicato/PizzG.Eb5.mp3",
  "PizzG.F4" : "./Instruments/Strings/Viola/Pizzicato/PizzG.F4.mp3",
  "PizzG.F5" : "./Instruments/Strings/Viola/Pizzicato/PizzG.F5.mp3",
  "PizzG.G3" : "./Instruments/Strings/Viola/Pizzicato/PizzG.G3.mp3",
  "PizzG.G4" : "./Instruments/Strings/Viola/Pizzicato/PizzG.G4.mp3",
  "PizzG.G5" : "./Instruments/Strings/Viola/Pizzicato/PizzG.G5.mp3",
  "PizzG.Gb4" : "./Instruments/Strings/Viola/Pizzicato/PizzG.Gb4.mp3",
  "PizzG.Gb5" : "./Instruments/Strings/Viola/Pizzicato/PizzG.Gb5.mp3",
});

Arcoviola.toMaster();
Arcoviola.volume.value = -35;

Pizzviola.toMaster();

Arcoviola.set({
    "player" : {
    //"loop" : true,
    "loopStart" : 1,
    "loopEnd" : 1.2
  }
})

Pizzviola.set({
    "player" : {
    "loop" : true,
    "loopStart" : 1,
    "loopEnd" : 1.02,
  }
})

Tone.Buffer.onload = function(){
  
  console.log("loaded");

  Arcoviola.triggerAttackRelease("A.E5", "8n");
  
};
 
//   for more acoustic samples, you can download instruments recorded in an anechoic chamber from: 
//   http://theremin.music.uiowa.edu/MIS.html
